[build-system]
requires = ["setuptools>=56", "setuptools_scm[toml]>=3.4.1"]
build-backend = "setuptools.build_meta"

[tool.black]
skip-string-normalization = true

[tool.setuptools_scm]

[pytest.enabler.black]
# disabled for pytest-dev/pytest#8332
# addopts = "--black"

[pytest.enabler.mypy]
# disabled for pytest-dev/pytest#8332
# addopts = "--mypy"

[pytest.enabler.flake8]
# disabled for pytest-dev/pytest#8332
# addopts = "--flake8"

[pytest.enabler.cov]
addopts = "--cov"
